import { CategoryId, CategoryInfo } from '../types';

export const CATEGORIES: CategoryInfo[] = [
  // Top 100 Hub
  {
    id: 'top-100',
    label: 'Top 100 Global',
    icon: '🏆',
    badge: 'All-Time Legends',
    description: 'Top 100 highest rated global cinema blockbusters',
    mediaType: 'both',
  },
  // 12 Core GOO TV Categories
  {
    id: 'hindi-movies',
    label: 'Hindi Movies',
    icon: '🇮🇳',
    badge: 'Bollywood',
    description: 'Latest & blockbuster Bollywood movies in Hindi',
    mediaType: 'movie',
  },
  {
    id: 'english-movies',
    label: 'English Movies',
    icon: '🇺🇸',
    badge: 'Hollywood',
    description: 'Top Hollywood blockbuster & English cinema',
    mediaType: 'movie',
  },
  {
    id: 'punjabi-movies',
    label: 'Punjabi Movies',
    icon: '🟠',
    badge: 'Pollywood',
    description: 'Top Punjabi comedy, drama, and action films',
    mediaType: 'movie',
  },
  {
    id: 'south-movies',
    label: 'South Movies',
    icon: '🌴',
    badge: 'Tamil • Telugu • Malayalam • Kannada',
    description: 'Blockbusters from South Indian film industries',
    mediaType: 'movie',
    subcategories: [
      { id: 'all', label: 'All South', langCode: 'all' },
      { id: 'tamil', label: 'Tamil', langCode: 'ta' },
      { id: 'telugu', label: 'Telugu', langCode: 'te' },
      { id: 'malayalam', label: 'Malayalam', langCode: 'ml' },
      { id: 'kannada', label: 'Kannada', langCode: 'kn' },
    ],
  },
  {
    id: 'classic-movies',
    label: 'Classic Movies',
    icon: '🕰️',
    badge: 'Vintage & Golden Era',
    description: 'Timeless masterpieces released before 2000',
    mediaType: 'movie',
  },
  {
    id: 'hindi-dubbed-movies',
    label: 'Hindi Dubbed Movies',
    icon: '🎙️',
    badge: 'Dual Audio / Hindi',
    description: 'Hollywood & South blockbusters dubbed in Hindi',
    mediaType: 'movie',
  },
  {
    id: 'k-drama',
    label: 'K-Drama',
    icon: '🇰🇷',
    badge: 'Korean Drama',
    description: 'Popular Korean romantic & suspense drama series',
    mediaType: 'tv',
  },
  {
    id: 'hindi-dubbed-kdrama',
    label: 'Hindi Dubbed K-Drama',
    icon: '🇮🇳🇰🇷',
    badge: 'K-Drama in Hindi',
    description: 'Top rated Korean series with official Hindi audio',
    mediaType: 'tv',
  },
  {
    id: 'hbo-movies',
    label: 'HBO Movies',
    icon: '🔵',
    badge: 'HBO & Warner',
    description: 'Acclaimed HBO Originals & Warner Bros cinema',
    mediaType: 'both',
  },
  {
    id: 'netflix-movies',
    label: 'Netflix Movies',
    icon: '🔴',
    badge: 'Netflix Originals',
    description: 'Global and Indian Netflix exclusive movies & shows',
    mediaType: 'both',
  },
  {
    id: 'jiohotstar-movies',
    label: 'JioHotstar Movies',
    icon: '🟣',
    badge: 'Hotstar & JioCinema',
    description: 'Blockbuster hits from JioCinema & Disney+ Hotstar',
    mediaType: 'both',
  },
  {
    id: 'mxplayer-movies',
    label: 'MX Player Movies',
    icon: '🟢',
    badge: 'MX Player & Desi',
    description: 'Top MX Player original web series and desi movies',
    mediaType: 'both',
  },
  // Worldwide Movies Categories (World Cinema Hub)
  {
    id: 'japanese-anime',
    label: 'Japanese & Anime',
    icon: '🇯🇵',
    badge: 'Anime & Tokyo',
    description: 'Top Japanese animated movies and action cinema',
    mediaType: 'both',
    isWorldCinema: true,
  },
  {
    id: 'spanish-movies',
    label: 'Spanish Cinema',
    icon: '🇪🇸',
    badge: 'España & Latin',
    description: 'Thrilling Spanish, Mexican, and Latin American movies',
    mediaType: 'movie',
    isWorldCinema: true,
  },
  {
    id: 'french-movies',
    label: 'French Cinema',
    icon: '🇫🇷',
    badge: 'Français',
    description: 'Acclaimed French art, comedy, and thriller films',
    mediaType: 'movie',
    isWorldCinema: true,
  },
  {
    id: 'turkish-movies',
    label: 'Turkish Drama & Dizi',
    icon: '🇹🇷',
    badge: 'Türkçe',
    description: 'Popular Turkish romantic and historical dramas',
    mediaType: 'both',
    isWorldCinema: true,
  },
  {
    id: 'chinese-movies',
    label: 'Chinese & HK Cinema',
    icon: '🇨🇳',
    badge: 'Martial Arts & HK',
    description: 'Iconic Hong Kong martial arts and Chinese blockbusters',
    mediaType: 'movie',
    isWorldCinema: true,
  },
  {
    id: 'german-movies',
    label: 'German Cinema',
    icon: '🇩🇪',
    badge: 'Deutsch',
    description: 'Gripping German cinema, sci-fi, and crime series',
    mediaType: 'both',
    isWorldCinema: true,
  },
  {
    id: 'arabic-movies',
    label: 'Arabic Cinema',
    icon: '🇸🇦',
    badge: 'العربية',
    description: 'Middle Eastern and North African drama & comedy',
    mediaType: 'movie',
    isWorldCinema: true,
  },
];
