import { CategoryId, CategoryGroup, CategoryInfo } from '../types';

export const CATEGORY_GROUPS: { id: CategoryGroup; label: string; icon: string }[] = [
  { id: 'trending', label: '🔥 Global Trending', icon: '🔥' },
  { id: 'industry', label: '🎥 Film Industries', icon: '🎥' },
  { id: 'animation', label: '🎨 Animation & Anime', icon: '🎨' },
  { id: 'language', label: '🗣️ Languages', icon: '🗣️' },
  { id: 'dubbed', label: '🎙️ Hindi & Dubbed', icon: '🎙️' },
  { id: 'ott', label: '📺 OTT Platforms', icon: '📺' },
  { id: 'genre', label: '🎭 Genres', icon: '🎭' },
  { id: 'series', label: '📺 TV & Web Series', icon: '📺' },
];

export const CATEGORIES: CategoryInfo[] = [
  // ==========================================
  // PRIMARY 16 RECOMMENDATION CATEGORIES (TOP BAR)
  // ==========================================
  {
    id: 'trending',
    label: 'Global Trending',
    icon: '🔥',
    badge: 'Worldwide Trending',
    description: 'Most popular and talked-about movies & series across the globe',
    mediaType: 'both',
    group: 'trending',
    isPrimary: true,
  },
  {
    id: 'global-blockbusters',
    label: 'Global Blockbusters',
    icon: '💥',
    badge: 'Box Office Hits',
    description: 'High-budget blockbuster hits with worldwide popularity',
    mediaType: 'movie',
    group: 'trending',
    isPrimary: true,
  },
  {
    id: 'hollywood-movies',
    label: 'Hollywood Movies',
    icon: '🎬',
    badge: 'Mainstream US Cinema',
    description: 'Top Hollywood theatrical cinema and American productions',
    mediaType: 'movie',
    group: 'industry',
    isPrimary: true,
  },
  {
    id: 'bollywood-movies',
    label: 'Bollywood Movies',
    icon: '🇮🇳',
    badge: 'Hindi Cinema',
    description: 'Latest and timeless Hindi cinema from Mumbai',
    mediaType: 'movie',
    group: 'industry',
    isPrimary: true,
  },
  {
    id: 'south-movies',
    label: 'South Indian Movies',
    icon: '🌴',
    badge: 'Tamil • Telugu • Malayalam • Kannada',
    description: 'High-octane blockbusters from South Indian film industries',
    mediaType: 'movie',
    group: 'industry',
    isPrimary: true,
    subcategories: [
      { id: 'all', label: 'All South', langCode: 'all' },
      { id: 'telugu', label: 'Telugu (Tollywood)', langCode: 'te' },
      { id: 'tamil', label: 'Tamil (Kollywood)', langCode: 'ta' },
      { id: 'malayalam', label: 'Malayalam (Mollywood)', langCode: 'ml' },
      { id: 'kannada', label: 'Kannada (Sandalwood)', langCode: 'kn' },
    ],
  },
  {
    id: 'punjabi-movies',
    label: 'Punjabi Movies',
    icon: '🎞️',
    badge: 'Pollywood',
    description: 'Punjabi comedy, drama, and action films from Punjab & diaspora',
    mediaType: 'movie',
    group: 'industry',
    isPrimary: true,
  },
  {
    id: 'animation-movies',
    label: 'Animation & Kids',
    icon: '🎨',
    badge: 'Family & 3D Disney/Pixar',
    description: 'Top rated animated masterpieces for kids and families worldwide',
    mediaType: 'movie',
    group: 'animation',
    isPrimary: true,
  },
  {
    id: 'k-drama',
    label: 'Korean & K-Drama',
    icon: '🇰🇷',
    badge: 'Hallyu Wave',
    description: 'Addictive Korean drama series and thrilling cinema',
    mediaType: 'tv',
    group: 'series',
    isPrimary: true,
  },
  {
    id: 'chinese-movies',
    label: 'Chinese & C-Drama',
    icon: '🇨🇳',
    badge: 'Martial Arts & Historical',
    description: 'Chinese epic historical series, wuxia, and blockbusters',
    mediaType: 'both',
    group: 'industry',
    isPrimary: true,
  },
  {
    id: 'world-cinema',
    label: 'World Cinema',
    icon: '🌏',
    badge: 'Global Independent',
    description: 'Critically acclaimed international cinema across 50+ nations',
    mediaType: 'movie',
    group: 'industry',
    isPrimary: true,
    isWorldCinema: true,
  },
  {
    id: 'hindi-dubbed-movies',
    label: 'Hindi Dubbed Movies',
    icon: '🎙️',
    badge: 'Verified Dual Audio',
    description: 'Hollywood, South, and international films dubbed into Hindi',
    mediaType: 'movie',
    group: 'dubbed',
    isPrimary: true,
  },
  {
    id: 'classic-movies',
    label: 'All-Time Classics',
    icon: '👑',
    badge: 'Golden Era Legends',
    description: 'Evergreen cinematic masterpieces released before 2000',
    mediaType: 'movie',
    group: 'trending',
    isPrimary: true,
  },
  {
    id: 'netflix-movies',
    label: 'Netflix Originals',
    icon: '🔴',
    badge: 'Netflix Exclusive',
    description: 'Original movies and international releases from Netflix',
    mediaType: 'both',
    group: 'ott',
    isPrimary: true,
  },
  {
    id: 'hbo-movies',
    label: 'HBO & Warner',
    icon: '🔵',
    badge: 'HBO Max Originals',
    description: 'Award-winning HBO series and Warner Bros cinematic titles',
    mediaType: 'both',
    group: 'ott',
    isPrimary: true,
  },
  {
    id: 'jiohotstar-movies',
    label: 'JioHotstar Movies',
    icon: '🟣',
    badge: 'Disney+ Hotstar & Jio',
    description: 'Hotstar specials, Marvel, Star Wars & JioCinema movies',
    mediaType: 'both',
    group: 'ott',
    isPrimary: true,
  },
  {
    id: 'mxplayer-movies',
    label: 'MX Player & Desi',
    icon: '🟢',
    badge: 'Desi Web Series',
    description: 'Desi crime, drama, and romance series from MX Player',
    mediaType: 'both',
    group: 'ott',
    isPrimary: true,
  },

  // ==========================================
  // GROUP 1: GLOBAL TRENDING & POPULAR CATEGORIES
  // ==========================================
  {
    id: 'global-box-office',
    label: 'Global Box Office',
    icon: '🌎',
    badge: 'Highest Grossing',
    description: 'Worldwide highest grossing box office earners of all time',
    mediaType: 'movie',
    group: 'trending',
  },
  {
    id: 'popular-movies',
    label: 'Popular Movies',
    icon: '⭐',
    badge: 'Top Worldwide Stream',
    description: 'Most searched and actively watched movies across platforms',
    mediaType: 'movie',
    group: 'trending',
  },
  {
    id: 'trending-tv',
    label: 'Trending TV Shows',
    icon: '📈',
    badge: 'Binge-Worthy TV',
    description: 'Current trending series and drama episodes globally',
    mediaType: 'tv',
    group: 'trending',
  },
  {
    id: 'new-releases',
    label: 'New Releases',
    icon: '🆕',
    badge: 'Latest In Theaters',
    description: 'Fresh cinematic releases from 2024 to 2026',
    mediaType: 'movie',
    group: 'trending',
  },
  {
    id: 'upcoming-movies',
    label: 'Upcoming Movies',
    icon: '🎬',
    badge: 'Trailers & Teasers',
    description: 'Anticipated upcoming titles scheduled for world premiere',
    mediaType: 'movie',
    group: 'trending',
  },
  {
    id: 'top-rated',
    label: 'Top Rated Movies',
    icon: '🏆',
    badge: 'IMDb 8.0+ Verified',
    description: 'Highest audience and critic rated movies with 1000+ votes',
    mediaType: 'movie',
    group: 'trending',
  },
  {
    id: 'hidden-gems',
    label: 'Hidden Gems',
    icon: '💎',
    badge: 'High Rating • Underrated',
    description: 'Exceptional movies with high ratings that you might have missed',
    mediaType: 'movie',
    group: 'trending',
  },
  {
    id: 'recommended',
    label: 'Recommended for You',
    icon: '🎯',
    badge: 'Curated Picks',
    description: 'Hand-picked selections tailored to your viewing tastes',
    mediaType: 'both',
    group: 'trending',
  },
  {
    id: 'top-100',
    label: 'Top 100 Global',
    icon: '🏆',
    badge: 'All-Time Legends',
    description: 'Top 100 highest rated global cinema blockbusters of all time',
    mediaType: 'both',
    group: 'trending',
  },

  // ==========================================
  // GROUP 2: MOVIES BY FILM INDUSTRY
  // ==========================================
  {
    id: 'korean-movies',
    label: 'Korean Cinema',
    icon: '🇰🇷',
    badge: 'Chungmuro Cinema',
    description: 'Critically acclaimed South Korean thrillers, horror & drama',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'japanese-movies',
    label: 'Japanese Cinema',
    icon: '🇯🇵',
    badge: 'Nippon Cinema',
    description: 'Japanese live-action cinema, samurai epics & drama',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'french-movies',
    label: 'French Cinema',
    icon: '🇫🇷',
    badge: 'Cinéma Français',
    description: 'Acclaimed French art, comedy, and psychological thrillers',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'spanish-movies',
    label: 'Spanish & Latin Cinema',
    icon: '🇪🇸',
    badge: 'Cine Español',
    description: 'Thrilling Spanish, Mexican, and Latin American movies',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'german-movies',
    label: 'German Cinema',
    icon: '🇩🇪',
    badge: 'Deutsches Kino',
    description: 'Gripping German cinema, sci-fi, and historical drama',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'italian-movies',
    label: 'Italian Cinema',
    icon: '🇮🇹',
    badge: 'Cinema Italiano',
    description: 'Legendary Italian drama, romance, crime and neorealism',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'russian-movies',
    label: 'Russian Cinema',
    icon: '🇷🇺',
    badge: 'Российское кино',
    description: 'Epic Russian sci-fi, war, space and historical cinema',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'turkish-movies',
    label: 'Turkish Cinema',
    icon: '🇹🇷',
    badge: 'Türk Sineması',
    description: 'Emotional and dramatic Turkish cinema masterpieces',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'thai-movies',
    label: 'Thai Cinema',
    icon: '🇹🇭',
    badge: 'Muay Thai & Horror',
    description: 'Famous Thai martial arts and legendary horror movies',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'indonesian-movies',
    label: 'Indonesian Cinema',
    icon: '🇮🇩',
    badge: 'Pencak Silat & Horror',
    description: 'Hard-hitting Indonesian action cinema like The Raid',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'filipino-movies',
    label: 'Filipino Cinema',
    icon: '🇵🇭',
    badge: 'Pinoy Cinema',
    description: 'Heartwarming Pinoy drama, romance, and indie thrillers',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'african-cinema',
    label: 'African Cinema (Nollywood)',
    icon: '🌍',
    badge: 'Nollywood & Africa',
    description: 'Vibrant films from Nigeria, South Africa and across the continent',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'latin-cinema',
    label: 'Latin American Cinema',
    icon: '🌎',
    badge: 'Brazil & Mexico',
    description: 'Passionate cinema from Brazil, Argentina, and Colombia',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },
  {
    id: 'middle-east-cinema',
    label: 'Middle Eastern Cinema',
    icon: '🕌',
    badge: 'Arab & Iranian',
    description: 'Acclaimed Iranian and Arab drama and storytelling',
    mediaType: 'movie',
    group: 'industry',
    isWorldCinema: true,
  },

  // Aliases for backward compatibility
  {
    id: 'hindi-movies',
    label: 'Hindi Movies',
    icon: '🇮🇳',
    badge: 'Bollywood',
    description: 'Latest & blockbuster Bollywood movies in Hindi',
    mediaType: 'movie',
    group: 'industry',
  },
  {
    id: 'english-movies',
    label: 'English Movies',
    icon: '🇺🇸',
    badge: 'Hollywood',
    description: 'Top Hollywood blockbuster & English cinema',
    mediaType: 'movie',
    group: 'industry',
  },

  // ==========================================
  // GROUP 3: ANIMATION, ANIME & FAMILY
  // ==========================================
  {
    id: 'kids-movies',
    label: 'Kids Movies',
    icon: '🧸',
    badge: 'Children Safe G-Rated',
    description: 'Fun and educational movies suitable for young children',
    mediaType: 'movie',
    group: 'animation',
  },
  {
    id: 'family-movies',
    label: 'Family Movies',
    icon: '👨👩👧',
    badge: 'Whole Family Enjoyment',
    description: 'Feel-good entertainment for the entire family to enjoy together',
    mediaType: 'movie',
    group: 'animation',
  },
  {
    id: 'anime-movies',
    label: 'Anime Movies',
    icon: '🇯🇵',
    badge: 'Studio Ghibli & Shonen',
    description: 'Japanese animated theatrical films like Makoto Shinkai & Ghibli',
    mediaType: 'movie',
    group: 'animation',
  },
  {
    id: 'anime-series',
    label: 'Anime Series',
    icon: '📺',
    badge: 'Shonen & Isekai Series',
    description: 'Top anime series: Jujutsu Kaisen, Demon Slayer, One Piece',
    mediaType: 'tv',
    group: 'animation',
  },
  {
    id: 'superhero-movies',
    label: 'Superhero Movies',
    icon: '🦸',
    badge: 'Marvel & DC Comics',
    description: 'Epic superhero battles from Marvel MCU, DC, and comic universes',
    mediaType: 'movie',
    group: 'animation',
  },
  {
    id: 'fantasy-movies',
    label: 'Fantasy Movies',
    icon: '🐉',
    badge: 'Magical Worlds',
    description: 'Dragons, wizards, mythical realms, and epic adventures',
    mediaType: 'movie',
    group: 'animation',
  },
  {
    id: 'scifi-movies',
    label: 'Sci-Fi Movies',
    icon: '🤖',
    badge: 'Futuristic & Alien',
    description: 'Mind-bending science fiction, space travel, and time warps',
    mediaType: 'movie',
    group: 'animation',
  },
  {
    id: 'classic-animation',
    label: 'Classic Animation',
    icon: '🕰️',
    badge: 'Vintage 2D Hand-Drawn',
    description: 'Nostalgic 2D animated classics from Disney and Warner',
    mediaType: 'movie',
    group: 'animation',
  },
  {
    id: 'adult-animation',
    label: 'Adult Animation (18+)',
    icon: '🎭',
    badge: 'Mature 18+ Animation',
    description: 'Dark, humorous, and philosophical animated titles for adults',
    mediaType: 'both',
    group: 'animation',
  },
  {
    id: 'japanese-anime',
    label: 'Anime & Manga All',
    icon: '🇯🇵',
    badge: 'Tokyo Anime Hub',
    description: 'Complete Japanese anime movies and series catalog',
    mediaType: 'both',
    group: 'animation',
  },

  // ==========================================
  // GROUP 4: MOVIES BY ORIGINAL LANGUAGE
  // ==========================================
  {
    id: 'lang-hindi',
    label: 'Hindi Language (हिन्दी)',
    icon: '🇮🇳',
    badge: 'Original Audio: Hindi',
    description: 'Movies filmed in Hindi as the original spoken dialogue',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-english',
    label: 'English Language',
    icon: '🇺🇸',
    badge: 'Original Audio: English',
    description: 'Movies filmed with original English spoken dialogue',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-punjabi',
    label: 'Punjabi Language (ਪੰਜਾਬੀ)',
    icon: '🟠',
    badge: 'Original Audio: Punjabi',
    description: 'Authentic Punjabi language cinema and web series',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-tamil',
    label: 'Tamil Language (தமிழ்)',
    icon: '🌴',
    badge: 'Original Audio: Tamil',
    description: 'Authentic Tamil language movies from Tamil Nadu',
    mediaType: 'movie',
    group: 'language',
  },
  {
    id: 'lang-telugu',
    label: 'Telugu Language (తెలుగు)',
    icon: '🌴',
    badge: 'Original Audio: Telugu',
    description: 'Authentic Telugu language movies from Tollywood',
    mediaType: 'movie',
    group: 'language',
  },
  {
    id: 'lang-malayalam',
    label: 'Malayalam (മലയാളം)',
    icon: '🌴',
    badge: 'Original Audio: Malayalam',
    description: 'Content-rich realistic Malayalam cinema',
    mediaType: 'movie',
    group: 'language',
  },
  {
    id: 'lang-kannada',
    label: 'Kannada Language (ಕನ್ನಡ)',
    icon: '🌴',
    badge: 'Original Audio: Kannada',
    description: 'Blockbusters and dramas in original Kannada language',
    mediaType: 'movie',
    group: 'language',
  },
  {
    id: 'lang-korean',
    label: 'Korean Language (한국어)',
    icon: '🇰🇷',
    badge: 'Original Audio: Korean',
    description: 'Original Korean language cinema and K-Drama',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-chinese',
    label: 'Chinese Language (中文)',
    icon: '🇨🇳',
    badge: 'Original Audio: Mandarin/Cantonese',
    description: 'Original Mandarin and Cantonese cinema and dramas',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-japanese',
    label: 'Japanese Language (日本語)',
    icon: '🇯🇵',
    badge: 'Original Audio: Japanese',
    description: 'Original Japanese audio movies and anime',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-russian',
    label: 'Russian Language (Русский)',
    icon: '🇷🇺',
    badge: 'Original Audio: Russian',
    description: 'Cinema produced with original Russian audio',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-spanish',
    label: 'Spanish Language (Español)',
    icon: '🇪🇸',
    badge: 'Original Audio: Spanish',
    description: 'Movies filmed in Spanish across Spain and Latin America',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-french',
    label: 'French Language (Français)',
    icon: '🇫🇷',
    badge: 'Original Audio: French',
    description: 'Cinema produced with original French audio dialogue',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-german',
    label: 'German Language (Deutsch)',
    icon: '🇩🇪',
    badge: 'Original Audio: German',
    description: 'Cinema with original German audio dialogue',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-arabic',
    label: 'Arabic Language (العربية)',
    icon: '🇸🇦',
    badge: 'Original Audio: Arabic',
    description: 'Original Arabic language movies and series',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-turkish',
    label: 'Turkish Language (Türkçe)',
    icon: '🇹🇷',
    badge: 'Original Audio: Turkish',
    description: 'Original Turkish audio series (diziler) and films',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-thai',
    label: 'Thai Language (ไทย)',
    icon: '🇹🇭',
    badge: 'Original Audio: Thai',
    description: 'Original Thai dialogue action and horror films',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-indonesian',
    label: 'Indonesian (Bahasa)',
    icon: '🇮🇩',
    badge: 'Original Audio: Indonesian',
    description: 'Original Indonesian language films and shows',
    mediaType: 'both',
    group: 'language',
  },
  {
    id: 'lang-portuguese',
    label: 'Portuguese (Português)',
    icon: '🇧🇷',
    badge: 'Original Audio: Portuguese',
    description: 'Films with original Portuguese dialogue from Brazil & Portugal',
    mediaType: 'both',
    group: 'language',
  },

  // ==========================================
  // GROUP 5: HINDI DUBBED & OTHER DUBBED CONTENT
  // ==========================================
  {
    id: 'hindi-dubbed-hollywood',
    label: 'Hindi Dubbed Hollywood',
    icon: '🎙️🇺🇸',
    badge: 'Dual Audio (Hindi + Eng)',
    description: 'Hollywood blockbusters with verified high quality Hindi dubbing',
    mediaType: 'movie',
    group: 'dubbed',
  },
  {
    id: 'hindi-dubbed-south',
    label: 'Hindi Dubbed South Movies',
    icon: '🎙️🌴',
    badge: 'South in Hindi',
    description: 'South Indian action blockbusters dubbed in Hindi for all-India',
    mediaType: 'movie',
    group: 'dubbed',
  },
  {
    id: 'hindi-dubbed-korean',
    label: 'Hindi Dubbed Korean Movies',
    icon: '🎙️🇰🇷',
    badge: 'Korean in Hindi',
    description: 'Top Korean thrillers and zombie movies with Hindi audio',
    mediaType: 'movie',
    group: 'dubbed',
  },
  {
    id: 'hindi-dubbed-kdrama',
    label: 'Hindi Dubbed K-Drama',
    icon: '🎙️🇰🇷',
    badge: 'K-Drama in Hindi',
    description: 'Korean hit drama series officially dubbed in Hindi',
    mediaType: 'tv',
    group: 'dubbed',
  },
  {
    id: 'hindi-dubbed-chinese',
    label: 'Hindi Dubbed Chinese',
    icon: '🎙️🇨🇳',
    badge: 'Chinese in Hindi',
    description: 'Chinese kung fu & fantasy movies with Hindi audio tracks',
    mediaType: 'movie',
    group: 'dubbed',
  },
  {
    id: 'hindi-dubbed-anime',
    label: 'Hindi Dubbed Anime',
    icon: '🎙️🇯🇵',
    badge: 'Anime in Hindi',
    description: 'Anime movies and series featuring official Hindi voice actors',
    mediaType: 'both',
    group: 'dubbed',
  },
  {
    id: 'english-dubbed-anime',
    label: 'English Dubbed Anime',
    icon: '🎙️🇺🇸',
    badge: 'English Dub Anime',
    description: 'Anime series with verified English dubbing tracks',
    mediaType: 'both',
    group: 'dubbed',
  },
  {
    id: 'english-dubbed-movies',
    label: 'English Dubbed Movies',
    icon: '🎙️🌐',
    badge: 'English Dubbed',
    description: 'Foreign world cinema titles dubbed in English audio',
    mediaType: 'movie',
    group: 'dubbed',
  },
  {
    id: 'multi-audio-movies',
    label: 'Multi-Audio Movies',
    icon: '🎧',
    badge: '5+ Audio Tracks',
    description: 'Titles offering multiple dual-audio channels (Hindi, Eng, Tamil)',
    mediaType: 'movie',
    group: 'dubbed',
  },
  {
    id: 'subtitled-movies',
    label: 'Movies with Subtitles',
    icon: '💬',
    badge: 'Multi-Lang Subtitles',
    description: 'International cinema with verified English and multilingual subs',
    mediaType: 'movie',
    group: 'dubbed',
  },
  {
    id: 'hindi-subtitles',
    label: 'Hindi Subtitles (CC)',
    icon: '💬🇮🇳',
    badge: 'हिन्दी Subtitles',
    description: 'Foreign language movies with verified Hindi subtitles',
    mediaType: 'movie',
    group: 'dubbed',
  },

  // ==========================================
  // GROUP 6: OTT & STREAMING PLATFORMS
  // ==========================================
  {
    id: 'netflix-series',
    label: 'Netflix Series',
    icon: '🔴',
    badge: 'Netflix TV Shows',
    description: 'Binge-worthy original series from Netflix global studios',
    mediaType: 'tv',
    group: 'ott',
  },
  {
    id: 'hbo-series',
    label: 'HBO Series & Max',
    icon: '🔵',
    badge: 'HBO High Prestige',
    description: 'Prestige television drama and mini-series from HBO and Max',
    mediaType: 'tv',
    group: 'ott',
  },
  {
    id: 'jiohotstar-shows',
    label: 'JioHotstar Series',
    icon: '🟣',
    badge: 'Hotstar Specials',
    description: 'Indian and international streaming shows on Hotstar',
    mediaType: 'tv',
    group: 'ott',
  },
  {
    id: 'prime-video',
    label: 'Amazon Prime Video',
    icon: '📦',
    badge: 'Prime Originals',
    description: 'Exclusive movies and series available on Prime Video',
    mediaType: 'both',
    group: 'ott',
  },
  {
    id: 'disney-plus',
    label: 'Disney+ Originals',
    icon: '🏰',
    badge: 'Disney • Marvel • Star Wars',
    description: 'Blockbuster content from Disney, Marvel, Pixar and Lucasfilm',
    mediaType: 'both',
    group: 'ott',
  },
  {
    id: 'apple-tv',
    label: 'Apple TV+ Originals',
    icon: '🍏',
    badge: 'Award-Winning TV+',
    description: 'Aesthetic, high-concept original cinema and series from Apple',
    mediaType: 'both',
    group: 'ott',
  },
  {
    id: 'hulu',
    label: 'Hulu Exclusives',
    icon: '🟢',
    badge: 'Hulu Originals',
    description: 'Acclaimed comedies, dramas and true crime from Hulu',
    mediaType: 'both',
    group: 'ott',
  },
  {
    id: 'paramount-plus',
    label: 'Paramount+ Movies',
    icon: '⛰️',
    badge: 'Paramount Pictures',
    description: 'Iconic Paramount films and Yellowstone universe series',
    mediaType: 'both',
    group: 'ott',
  },
  {
    id: 'peacock',
    label: 'Peacock Universal',
    icon: '🦚',
    badge: 'Universal & NBC',
    description: 'Universal Pictures cinema and NBC series on Peacock',
    mediaType: 'both',
    group: 'ott',
  },
  {
    id: 'sonyliv',
    label: 'SonyLIV Specials',
    icon: '💎',
    badge: 'Indian Originals',
    description: 'Critically acclaimed Indian crime, drama and thrillers on SonyLIV',
    mediaType: 'both',
    group: 'ott',
  },
  {
    id: 'zee5',
    label: 'ZEE5 Originals',
    icon: '⭐',
    badge: 'Desi Regional',
    description: 'Regional Indian blockbusters and original series from ZEE5',
    mediaType: 'both',
    group: 'ott',
  },
  {
    id: 'crunchyroll',
    label: 'Crunchyroll Anime',
    icon: '🍥',
    badge: 'Simulcast Anime',
    description: 'Licensed Japanese anime direct streaming from Crunchyroll',
    mediaType: 'both',
    group: 'ott',
  },

  // ==========================================
  // GROUP 7: GENRE CATEGORIES
  // ==========================================
  {
    id: 'action-movies',
    label: 'Action',
    icon: '💥',
    badge: 'High Octane Action',
    description: 'Explosive blockbuster action, martial arts, stunts and car chases',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'adventure-movies',
    label: 'Adventure',
    icon: '🧭',
    badge: 'Epic Expeditions',
    description: 'Thrilling journeys, treasure hunts, and wilderness survival',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'comedy-movies',
    label: 'Comedy',
    icon: '😂',
    badge: 'Laugh Out Loud',
    description: 'Hilarious comedy, satire, parodies, and lighthearted humor',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'crime-movies',
    label: 'Crime & Mob',
    icon: '🕵️',
    badge: 'Underworld & Gangster',
    description: 'Gritty crime syndicates, heists, mobsters, and detective noir',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'drama-movies',
    label: 'Drama',
    icon: '🎭',
    badge: 'Emotional & Realistic',
    description: 'Deeply touching human stories, conflicts, and character studies',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'horror-movies',
    label: 'Horror',
    icon: '👻',
    badge: 'Supernatural & Slasher',
    description: 'Spine-chilling paranormal entities, psychological dread & monsters',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'thriller-movies',
    label: 'Thriller',
    icon: '⚡',
    badge: 'Suspense & Edge of Seat',
    description: 'Nail-biting suspense, plot twists, espionage, and psychological danger',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'mystery-movies',
    label: 'Mystery',
    icon: '🔍',
    badge: 'Whodunnit & Enigma',
    description: 'Puzzling crimes, detective cases, and secret unravelings',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'romance-movies',
    label: 'Romance & Love',
    icon: '❤️',
    badge: 'Love & Heartbreak',
    description: 'Soul-stirring romance, love stories, and emotional bonds',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'war-movies',
    label: 'War & Combat',
    icon: '⚔️',
    badge: 'Battlefield History',
    description: 'Historical warfare, battlefield courage, and military sagas',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'history-movies',
    label: 'History & Epic',
    icon: '🏛️',
    badge: 'True Historical Eras',
    description: 'Fascinating period dramas, royal empires, and real events',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'documentary-movies',
    label: 'Documentary',
    icon: '📹',
    badge: 'Real World Truths',
    description: 'Insightful real-life documentaries, nature, science and crime',
    mediaType: 'both',
    group: 'genre',
  },
  {
    id: 'music-movies',
    label: 'Music & Musical',
    icon: '🎵',
    badge: 'Musical & Concert',
    description: 'Musical performances, artist biopics, and soundtrack-driven stories',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'western-movies',
    label: 'Western',
    icon: '🤠',
    badge: 'Cowboys & Frontier',
    description: 'Wild west gunfighters, outlaws, frontiersmen, and duels',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'sports-movies',
    label: 'Sports Cinema',
    icon: '🏆',
    badge: 'Underdog Victory',
    description: 'Inspiring athletic competitions, championships, and underdogs',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'biography-movies',
    label: 'Biography',
    icon: '📜',
    badge: 'True Life Stories',
    description: 'Remarkable true stories of inspiring historical and modern icons',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'disaster-movies',
    label: 'Disaster & Survival',
    icon: '🌋',
    badge: 'Catastrophe & Chaos',
    description: 'Volcanic eruptions, earthquakes, tsunamis, and survival struggles',
    mediaType: 'movie',
    group: 'genre',
  },
  {
    id: 'martial-arts',
    label: 'Martial Arts',
    icon: '🥋',
    badge: 'Kung Fu & Karate',
    description: 'Hand-to-hand combat, wuxia, samurai duels, and martial arts masters',
    mediaType: 'movie',
    group: 'genre',
  },

  // ==========================================
  // GROUP 8: TV SHOWS, WEB SERIES & DRAMAS
  // ==========================================
  {
    id: 'global-tv',
    label: 'Global TV Shows',
    icon: '📺',
    badge: 'Worldwide Television',
    description: 'International television series from across 6 continents',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'web-series',
    label: 'Web Series All',
    icon: '💻',
    badge: 'Multi-Season Binge',
    description: 'Top Indian & International web series all seasons in 4K',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'c-drama',
    label: 'Chinese Dramas (C-Drama)',
    icon: '🇨🇳',
    badge: 'Historical & Romance',
    description: 'Captivating Chinese historical, fantasy, and modern romance series',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'j-drama',
    label: 'Japanese Dramas (J-Drama)',
    icon: '🇯🇵',
    badge: 'Tokyo Drama',
    description: 'Intense and quirky Japanese live-action dramas and thrillers',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'turkish-drama',
    label: 'Turkish Dramas (Dizi)',
    icon: '🇹🇷',
    badge: 'Diziler',
    description: 'Globally popular Turkish emotional romantic and historical series',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'russian-series',
    label: 'Russian Series',
    icon: '🇷🇺',
    badge: 'Russian TV',
    description: 'High-concept Russian sci-fi, detective, and historical series',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'indian-web-series',
    label: 'Indian Web Series',
    icon: '🇮🇳',
    badge: 'Desi OTT Blockbusters',
    description: 'Gripping crime, thriller, and family web series from India',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'american-tv',
    label: 'American TV Shows',
    icon: '🇺🇸',
    badge: 'US Network & Cable',
    description: 'Top-rated American network, cable, and streaming television shows',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'british-tv',
    label: 'British TV Shows',
    icon: '🇬🇧',
    badge: 'BBC & ITV Masterpiece',
    description: 'Acclaimed British crime dramas, period mysteries, and comedies',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'mini-series',
    label: 'Mini-Series (Limited)',
    icon: '⏳',
    badge: 'Complete Single Story',
    description: 'High-impact limited series that tell a complete story in one season',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'crime-series',
    label: 'Crime Series',
    icon: '🚨',
    badge: 'True Crime & Syndicate',
    description: 'Addictive detective procedurals, serial killers, and cartels',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'reality-shows',
    label: 'Reality Shows',
    icon: '🎙️',
    badge: 'Unscripted TV',
    description: 'Celebrated unscripted competition, talent, and survival shows',
    mediaType: 'tv',
    group: 'series',
  },
  {
    id: 'arabic-movies',
    label: 'Arabic Cinema & Series',
    icon: '🇸🇦',
    badge: 'العربية',
    description: 'Middle Eastern and North African drama & comedy',
    mediaType: 'both',
    group: 'industry',
    isWorldCinema: true,
  },
];
